# Generated by Django 3.2.7 on 2021-09-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
